apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pedidos
  labels:
    strimzi.io/cluster: my-kraft-cluster
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 3600000   # 1 hora
    segment.bytes: 1073741824